import { HStack, VStack, Text, Button, Image } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <HStack className={styles.landingContainer}>
          <HStack gap={5}>
            <Image
              alt="5"
              src="/landing/5.png"
              className={styles.landingImage}
            ></Image>
            <VStack gap={5}>
              <Image
                alt="1"
                src="/landing/1.png"
                className={styles.landingImage}
              ></Image>
              <Image
                alt="2"
                src="/landing/2.png"
                className={styles.landingImage}
              ></Image>
            </VStack>
          </HStack>
          <VStack gap={5}>
            <Text className={styles.landingTitle}>Find a cause you love</Text>
            <Text className={styles.landingSubtitle}>
              Help others in need with crypto or fundraise for your own cause
            </Text>
            <Button className={styles.landingBtn}>Browse Causes</Button>
          </VStack>
          <HStack gap={5}>
            <VStack gap={5}>
              <Image
                alt="3"
                src="/landing/3.png"
                className={styles.landingImage}
              ></Image>
              <Image
                alt="4"
                src="/landing/4.png"
                className={styles.landingImage}
              ></Image>
            </VStack>
            <Image
              alt="6"
              src="/landing/6.png"
              className={styles.landingImage}
            ></Image>
          </HStack>
        </HStack>
      </main>
    </div>
  );
};

export default Home;
